// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQkVYmcRsQSgLJzXMRM-glq3x0dPTz1J4',
    appId: '1:81783431464:web:30e0ab995e028ea44bf01d',
    messagingSenderId: '81783431464',
    projectId: 'traumatrace-ec86a',
    authDomain: 'traumatrace-ec86a.firebaseapp.com',
    storageBucket: 'traumatrace-ec86a.firebasestorage.app',
    measurementId: 'G-77WHE0LZER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkFRhqPCkfAi3mSpIkZ3arF16D_XY_zx4',
    appId: '1:81783431464:android:02507dd4f630c2274bf01d',
    messagingSenderId: '81783431464',
    projectId: 'traumatrace-ec86a',
    storageBucket: 'traumatrace-ec86a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABdUWbrBWs9PFRNpGy9cYMXxvFp_BXDao',
    appId: '1:81783431464:ios:6bf63b1bca8025344bf01d',
    messagingSenderId: '81783431464',
    projectId: 'traumatrace-ec86a',
    storageBucket: 'traumatrace-ec86a.firebasestorage.app',
    iosBundleId: 'com.example.trauma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABdUWbrBWs9PFRNpGy9cYMXxvFp_BXDao',
    appId: '1:81783431464:ios:6bf63b1bca8025344bf01d',
    messagingSenderId: '81783431464',
    projectId: 'traumatrace-ec86a',
    storageBucket: 'traumatrace-ec86a.firebasestorage.app',
    iosBundleId: 'com.example.trauma',
  );
}
